---
- name: server restart playbook
  hosts: all
  vars:
    servicename: "{{ vars['servicename'] }}"
    operationname: "{{ vars['operationname'] }}"
  tasks:
    - name: Print parameters
      debug:
        msg: "hostname={{ hostname }} servicename={{ servicename }} operationname={{ operationname }}"
